//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/spinctrl.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#include "ZoomPanel.h"
#include <wx/menu.h>

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxStaticText* m_firstLabel;
    wxSpinCtrl* m_firstCtrl;
    wxStaticText* m_secondLabel;
    wxSpinCtrl* m_secondCtrl;
    wxStaticText* m_thirdLabel;
    wxSpinCtrl* m_thirdCtrl;
    wxStaticText* m_fourthLabel;
    wxSpinCtrl* m_fourthCtrl;
    wxPanel* m_colorButton;
    wxTextCtrl* m_formatText;
    wxButton* m_pickerButton;
    wxButton* m_button1281;
    wxButton* m_button128;
    wxButton* m_button12845;
    wxButton* m_timerButton;
    ZoomPanel* m_zoomPanel;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem9;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenuItem* m_menuItem79;
    wxMenu* m_menu65;
    wxMenu* m_colorModelMenu;
    wxMenu* m_colorOutputMenu;

protected:
    virtual void OnCaptureEnd(wxMouseEvent& event) { event.Skip(); }
    virtual void OnCaptureMove(wxMouseEvent& event) { event.Skip(); }
    virtual void OnCaptureZoom(wxMouseEvent& event) { event.Skip(); }
    virtual void OnColorChange(wxCommandEvent& event) { event.Skip(); }
    virtual void OnColorChange(wxSpinEvent& event) { event.Skip(); }
    virtual void OnColorOutputChange(wxCommandEvent& event) { event.Skip(); }
    virtual void OnInputOutputBlur(wxFocusEvent& event) { event.Skip(); }
    virtual void OnInputOutputEnter(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCaptureStart(wxMouseEvent& event) { event.Skip(); }
    virtual void OnZoomIn(wxCommandEvent& event) { event.Skip(); }
    virtual void OnZoomOut(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRefreshImage(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTimerRefreshImage(wxCommandEvent& event) { event.Skip(); }
    virtual void OnZoomPanelDown(wxMouseEvent& event) { event.Skip(); }
    virtual void OnZoomPanelUp(wxMouseEvent& event) { event.Skip(); }
    virtual void OnZoomPanelMove(wxMouseEvent& event) { event.Skip(); }
    virtual void OnZoomPanelZoom(wxMouseEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSystemColorPicker(wxCommandEvent& event) { event.Skip(); }

public:
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("ColorGrab"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxCAPTION|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX|wxSTAY_ON_TOP);
    virtual ~MainFrameBaseClass();
};

#endif
