//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/clrpicker.h>
#include <wx/button.h>
#include "ImagePanel.h"
#include <wx/menu.h>

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxPanel* m_panel31;
    wxStaticText* m_staticText35;
    wxTextCtrl* m_redCtrl;
    wxStaticText* m_staticText39;
    wxTextCtrl* m_greenCtrl;
    wxStaticText* m_staticText392;
    wxTextCtrl* m_blueCtrl;
    wxPanel* m_panel47;
    wxPanel* m_colorButton;
    wxColourPickerCtrl* m_colourPicker;
    wxPanel* m_panel55;
    wxTextCtrl* m_formatText;
    wxButton* m_pickerButton;
    ImagePanel* m_dumpImage;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem9;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenu* m_menu65;

protected:
    virtual void OnCaptureEnd(wxMouseEvent& event) { event.Skip(); }
    virtual void OnCaptureMove(wxMouseEvent& event) { event.Skip(); }
    virtual void OnColorChange(wxCommandEvent& event) { event.Skip(); }
    virtual void OnColorPick(wxColourPickerEvent& event) { event.Skip(); }
    virtual void OnCaptureStart(wxMouseEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }

public:
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("ColorGrab"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(240,300), long style = wxCAPTION|wxRESIZE_BORDER|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX|wxSTAY_ON_TOP);
    virtual ~MainFrameBaseClass();
};

#endif
